apiVersion: v1
kind: Service
metadata:
  name: netflixclone
spec:
  type: LoadBalancer
  selector:
    app: netflixclone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
